### PR TITLE
fixed sources to not produce any error in Eclipse

### PR DESCRIPTION
**Pull request by mareknovotny**
a fix of sources to get it working in Eclipse import and use Windup Eclipse plugin

### CODE REVIEW

**Comment by bergerhoffer** [comment]
I tested this and was able to successfully import the jee-migration-example-app projects now into Eclipse (before there was an error on import). 

However when I execute windup on jee-example-app, I see the report, but I don't see the project and issues in the Issue Explorer. Not sure if you see the same @mareknovotny.

**Comment by mareknovotny** [comment]
yep, there are some issues with the reports and Issue Explorer view see https://issues.jboss.org/browse/WINDUP-1288

**Comment by jsight** [comment]
Shouldn't this all just be a part of the sample-apps repo? https://github.com/windup/windup-sample-apps

**Comment by mareknovotny** [comment]
@jsight I don't know, it seems abandoned, latest commit 2014?

**Comment by d-s** [comment]
@mareknovotny Maybe we should bring the samples repo back to life (along with new lab apps we'll be developing this year) but for now, no reason not to merge this here I think?

**Comment by mareknovotny** [comment]
yep, I will do that

**Pull request merged**
